In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn import preprocessing #Convert categorical data to neumeric values
from sklearn.neural_network import MLPClassifier #Model being used

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/widsdatathon2023/train_data.csv
/kaggle/input/widsdatathon2023/test_data.csv
/kaggle/input/widsdatathon2023/sample_solution.csv

In [2]:
keep_columns=['lat','month','contest-tmp2m-14d__tmp2m',
              'climateregions__climateregion']

In [3]:
def seperate_monthly(df):
    df[['month','day','year']]=df.startdate.str.split('/',expand=True)
    df=df.drop('day', axis=1)
    df=df.drop('startdate',axis=1)
    return df

In [4]:
def eliminate_columns(df):
    for col in df.columns:
        if col in keep_columns:
            print(col)
        else: 
            df=df.drop(col, axis=1)
    return df

In [5]:
def seperate_y(df):
    y_df=df['contest-tmp2m-14d__tmp2m']
    X_df=df.drop('contest-tmp2m-14d__tmp2m',axis=1)
    return y_df,X_df

In [6]:
train_df=pd.read_csv('/kaggle/input/widsdatathon2023/train_data.csv')
train_df=train_df.dropna(axis=0)
test_df=pd.read_csv('/kaggle/input/widsdatathon2023/test_data.csv')
test_df=test_df.dropna(axis=0)
train_df

,index,lat,lon,startdate,contest-pevpr-sfc-gauss-14d__pevpr,nmme0-tmp2m-34w__cancm30,nmme0-tmp2m-34w__cancm40,nmme0-tmp2m-34w__ccsm30,nmme0-tmp2m-34w__ccsm40,nmme0-tmp2m-34w__cfsv20,...,wind-vwnd-925-2010-11,wind-vwnd-925-2010-12,wind-vwnd-925-2010-13,wind-vwnd-925-2010-14,wind-vwnd-925-2010-15,wind-vwnd-925-2010-16,wind-vwnd-925-2010-17,wind-vwnd-925-2010-18,wind-vwnd-925-2010-19,wind-vwnd-925-2010-20
0,0,0.0,0.833333,9/1/14,237.00,29.02,31.64,29.57,30.73,29.71,...,-27.68,-37.21,8.32,9.56,-2.03,48.13,28.09,-13.50,11.90,4.58
1,1,0.0,0.833333,9/2/14,228.90,29.02,31.64,29.57,30.73,29.71,...,-21.13,-36.57,8.77,21.17,4.44,48.60,27.41,-23.77,15.44,3.42
2,2,0.0,0.833333,9/3/14,220.69,29.02,31.64,29.57,30.73,29.71,...,-10.72,-34.16,6.99,32.16,5.01,48.53,19.21,-33.16,15.11,4.82
3,3,0.0,0.833333,9/4/14,225.28,29.02,31.64,29.57,30.73,29.71,...,0.33,-31.04,6.17,39.66,-1.41,50.59,8.29,-37.22,18.24,9.74
4,4,0.0,0.833333,9/5/14,237.24,29.02,31.64,29.57,30.73,29.71,...,9.83,-31.80,7.47,38.62,-5.21,54.73,-2.58,-42.30,21.91,10.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375729,375729,1.0,0.866667,8/27/16,312.05,23.13,27.20,20.25,24.43,18.35,...,-15.64,-75.68,-3.09,6.93,-16.69,16.98,-13.85,50.25,-31.33,0.77
375730,375730,1.0,0.866667,8/28/16,305.82,23.13,27.20,20.25,24.43,18.35,...,-7.59,-76.42,-13.55,13.36,-15.96,20.45,-16.36,51.65,-30.73,10.10
375731,375731,1.0,0.866667,8/29/16,311.62,23.13,27.20,20.25,24.43,18.35,...,-6.25,-70.65,-23.93,22.62,-16.71,20.28,-15.48,48.58,-18.74,9.28
375732,375732,1.0,0.866667,8/30/16,304.54,23.13,27.20,20.25,24.43,18.35,...,-7.16,-57.67,-33.55,32.06,-16.07,16.60,-20.61,39.23,-16.26,-0.22
375733,375733,1.0,0.866667,8/31/16,295.29,23.13,27.20,20.25,24.43,18.35,...,-12.36,-44.67,-32.46,36.25,-12.72,15.98,-22.56,32.53,-21.89,-1.20

In [7]:
train_df = train_df.sample(frac = 1)

In [8]:
le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
train_df['climateregions__climateregion']=le.fit_transform(train_df['climateregions__climateregion'])
test_df['climateregions__climateregion']=le.fit_transform(test_df['climateregions__climateregion'])

In [9]:
print('training set')
train_df=seperate_monthly(train_df)
train_df=eliminate_columns(train_df)
print('test set')
test_df=seperate_monthly(test_df)
test_df=eliminate_columns(test_df)

training set
lat
contest-tmp2m-14d__tmp2m
climateregions__climateregion
month
test set
lat
climateregions__climateregion
month

In [10]:
train_df

,lat,contest-tmp2m-14d__tmp2m,climateregions__climateregion,month
75144,0.363636,17.342348,3,4
356915,0.954545,3.189528,9,3
341932,0.954545,5.124009,11,3
63729,0.318182,1.663861,1,1
330255,0.909091,8.597452,1,3
...,...,...,...,...
61424,0.318182,13.206879,1,9
105319,0.409091,12.040933,1,10
154723,0.545455,-2.231986,7,12
260427,0.772727,5.950468,11,3
251872,0.727273,10.486349,1,10

In [11]:
y_train_df,X_train_df= seperate_y(train_df)

In [12]:
y_train_df=y_train_df.astype('int')

In [13]:
clf = MLPClassifier(hidden_layer_sizes=(2,10),
                    random_state=100,
                    verbose=True,
                    learning_rate_init=0.01)

# Fit data onto the model
clf.fit(X_train_df,y_train_df)

Iteration 1, loss = 3.37233055
Iteration 2, loss = 3.11954166
Iteration 3, loss = 3.10376529
Iteration 4, loss = 3.09673936
Iteration 5, loss = 3.09703477
Iteration 6, loss = 3.09312215
Iteration 7, loss = 3.09306875
Iteration 8, loss = 3.09101719
Iteration 9, loss = 3.09132715
Iteration 10, loss = 3.09038520
Iteration 11, loss = 3.08982081
Iteration 12, loss = 3.09035409
Iteration 13, loss = 3.08990187
Iteration 14, loss = 3.08872120
Iteration 15, loss = 3.08906110
Iteration 16, loss = 3.08800707
Iteration 17, loss = 3.08800465
Iteration 18, loss = 3.08742030
Iteration 19, loss = 3.08822367
Iteration 20, loss = 3.08798622
Iteration 21, loss = 3.08793997
Iteration 22, loss = 3.08679061
Iteration 23, loss = 3.08729340
Iteration 24, loss = 3.08709356
Iteration 25, loss = 3.08722929
Iteration 26, loss = 3.08707730
Iteration 27, loss = 3.08739890
Iteration 28, loss = 3.08813071
Iteration 29, loss = 3.08753955
Iteration 30, loss = 3.08671127
Iteration 31, loss = 3.08717310
Iteration 32, loss = 3.08701583
Iteration 33, loss = 3.08548669
Iteration 34, loss = 3.08554100
Iteration 35, loss = 3.08553554
Iteration 36, loss = 3.08491071
Iteration 37, loss = 3.08502949
Iteration 38, loss = 3.08497476
Iteration 39, loss = 3.08558787
Iteration 40, loss = 3.08420236
Iteration 41, loss = 3.08430559
Iteration 42, loss = 3.08353643
Iteration 43, loss = 3.08445437
Iteration 44, loss = 3.08416739
Iteration 45, loss = 3.08343605
Iteration 46, loss = 3.08426357
Iteration 47, loss = 3.08450296
Iteration 48, loss = 3.08338829
Iteration 49, loss = 3.08329043
Iteration 50, loss = 3.08400062
Iteration 51, loss = 3.08390765
Iteration 52, loss = 3.08392244
Iteration 53, loss = 3.08367580
Iteration 54, loss = 3.08301981
Iteration 55, loss = 3.08346866
Iteration 56, loss = 3.08431165
Iteration 57, loss = 3.08367350
Iteration 58, loss = 3.08362286
Iteration 59, loss = 3.08357564
Iteration 60, loss = 3.08319542
Iteration 61, loss = 3.08309463
Iteration 62, loss = 3.08344006
Iteration 63, loss = 3.08291998
Iteration 64, loss = 3.08316685
Iteration 65, loss = 3.08382106
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPClassifier(hidden_layer_sizes=(2, 10), learning_rate_init=0.01,
              random_state=100, verbose=True)

In [14]:
ypred=clf.predict(test_df)

In [15]:
#Trying to create a final 
final=pd.DataFrame()
final['contest-tmp2m-14d__tmp2m']=ypred
final['index']=0
i=375734 #Legnth of train_data.csv
while i<407088:
    final['index'][i-375734]=i
    i+=1
final

       contest-tmp2m-14d__tmp2m   index
0                             0  375734
1                             0  375735
2                             0  375736
3                             0  375737
4                             0  375738
...                         ...     ...
31349                         0  407083
31350                         0  407084
31351                         0  407085
31352                         0  407086
31353                         0  407087

[31354 rows x 2 columns]

In [16]:
final.to_csv('final.csv',index=False)

In [17]:
final

       contest-tmp2m-14d__tmp2m   index
0                             0  375734
1                             0  375735
2                             0  375736
3                             0  375737
4                             0  375738
...                         ...     ...
31349                         0  407083
31350                         0  407084
31351                         0  407085
31352                         0  407086
31353                         0  407087

[31354 rows x 2 columns]